name: KPubMC
version: 'v2.0.0'
main: xyz.jupp.minecraft.Main
api-version: '1.21'
description: "Offizielles Plugin für den KlotzscherPub Minecraft Server. (2025)"

commands:
  money:
  geld:
  schilling:
  config:
  hilfe:
  help:
  sc:
  slimechunk:
  einladungen:
  invites:
  team:
  ranking:
  createshop:
  hover:
  head:
  kopf:
  warp:
  customItem:
  donate:
  spenden:
  spawn:
  rules:
  regeln:
  createbankier:
  spec:
  createjuweler:
  createdealer:
  enderchest:
  ec:
  debug:
  createtpdealer:
  dummy:
  bestrafung:
  wanted:
