# /etc/ssh/sshd_config.d/10-hardening.conf
# __SSH_PORT__ und __ADMIN_USER__ ersetzt setup.sh
Port __SSH_PORT__
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
AllowUsers __ADMIN_USER__
MaxAuthTries 3
LoginGraceTime 20
MaxStartups 10:30:60
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
ClientAliveInterval 300
ClientAliveCountMax 2
